# Site settings
baseurl: "/0jekyll"
asseturl: "/assets"
name: "0jekyll"
skin: "classic"
lang:
 read_more: ">more>"
 postbytag: "10 bài có thẻ:"

# Build settings
markdown: redcarpet
permalink: /:categories/:title
paginate: 12
paginate_path: /page:num