# Site settings
baseurl: "/0jekyll" #/0jekyll
asseturl: "/0jekyll/assets"
name: "0jekyll"
skin: "classic"
lang:
 read_more: ">>"
 samecat: "Cùng mục"
 sametag: "Cùng thẻ"
 hotpost: "Bài nổi bật"
 subcat: "Chuyên mục" # name of sub folder
# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 6
paginate_path: /page:num

plugins: 
 - jekyll-paginate
