# Site settings
baseurl: "/0jekyll"
asseturl: "/assets"
name: "0jekyll"
skin: "classic"
lang:
 read_more: "...>>"

# Build settings
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
permalink: /:categories/:title
excerpt_separator: <!--more-->
paginate: 12
paginate_path: /page:num