# Site settings
baseurl: "/0jekyll"
asseturl: "/0jekyll/assets"
name: "0jekyll"
skin: "xmas"
lang:
 read_more: ">more>"
 postbytag: "Top10: "

# Build settings
markdown: redcarpet
permalink: /:categories/:title
paginate: 12
paginate_path: /page:num