# Site settings
baseurl: "/0jekyll"
asseturl: "/assets"
name: "0jekyll"
skin: "classic"
lang:
 read_more: "...>>"

# Build settings
markdown: redcarpet
permalink: /:categories/:title
excerpt_separator: \n\n
paginate: 12
paginate_path: /page:num