# Site settings
baseurl: "/news" # gh-pages/
asseturl: "/news/assets"
skin: "classic"
lang:
 read_more: ">>"
 samecat: "Xem thêm cùng mục"
 sametag: "Cùng thẻ"
 hotpost: "Bài nổi bật"
 subcat: "Chuyên mục" # name of sub folder
# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 10
paginate_path: /page:num

plugins: 
 - jekyll-paginate
